spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kpc
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: KPC Application
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
storage: /uploads
